AWSTemplateFormatVersion: "2010-09-09"
Description: 0131-AIF-Workshop Infrastructure

Resources:
  # ==========================================================
  # 1. S3 Buckets
  # ==========================================================
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - HEAD
            AllowedOrigins:
              - "*"
            ExposedHeaders:
              - ETag
      WebsiteConfiguration:
        IndexDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "${FrontendBucket.Arn}/*"

  GeneratedImagesBucket:
    Type: AWS::S3::Bucket
    DependsOn: S3BucketPermission
    Properties:
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - HEAD
            AllowedOrigins:
              - "*"
            ExposedHeaders:
              - ETag
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Function: !GetAtt NotifyFunction.Arn

  # ==========================================================
  # 2. DynamoDB
  # ==========================================================
  ConnectionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "WebSocketConnections-${AWS::StackName}"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: connectionId
          AttributeType: S
      KeySchema:
        - AttributeName: connectionId
          KeyType: HASH

  # ==========================================================
  # 3. IAM Roles
  # ==========================================================
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: WorkshopPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
              - Effect: Allow
                Action:
                  - sagemaker:InvokeEndpoint
                  - sagemaker:ListInferenceComponents
                Resource: "*"
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:DeleteItem
                  - dynamodb:Scan
                  - dynamodb:GetItem
                Resource: !GetAtt ConnectionsTable.Arn
              - Effect: Allow
                Action:
                  - execute-api:ManageConnections
                Resource: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*"
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                Resource: "*"

  # ==========================================================
  # 4. WebSocket API
  # ==========================================================
  WebSocketApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: GenAIWorkshopWebSocket
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: "$request.body.action"

  WebSocketStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref WebSocketApi
      StageName: production
      AutoDeploy: true

  # Routes
  ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: $connect
      Target: !Join ["/", ["integrations", !Ref ConnectIntegration]]

  DisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: $disconnect
      Target: !Join ["/", ["integrations", !Ref DisconnectIntegration]]

  GetIdRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: getId
      Target: !Join ["/", ["integrations", !Ref GetIdIntegration]]

  # Integrations
  ConnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt ConnectFunction.Arn

  DisconnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt ConnectFunction.Arn

  GetIdIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt ConnectFunction.Arn

  # ==========================================================
  # 5. Lambda Functions
  # ==========================================================

  ConnectFunction:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.11
      Handler: index.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref ConnectionsTable
      Code:
        ZipFile: |
          import boto3
          import os
          import json

          dynamodb = boto3.resource('dynamodb')
          table = dynamodb.Table(os.environ['TABLE_NAME'])

          def lambda_handler(event, context):
              route_key = event['requestContext']['routeKey']
              connection_id = event['requestContext']['connectionId']
              
              if route_key == '$connect':
                  print(f"New connection: {connection_id}")
                  table.put_item(Item={'connectionId': connection_id})
                  return {'statusCode': 200}
              
              elif route_key == '$disconnect':
                  print(f"Disconnected: {connection_id}")
                  try:
                      table.delete_item(Key={'connectionId': connection_id})
                  except Exception as e:
                      print(f"Error deleting connection: {e}")
                  return {'statusCode': 200}

              elif route_key == 'getId':
                  print(f"Client {connection_id} requesting ID")
                  domain = event['requestContext']['domainName']
                  stage = event['requestContext']['stage']
                  endpoint = f'https://{domain}/{stage}'
                  apigw = boto3.client('apigatewaymanagementapi', endpoint_url=endpoint)
                  
                  try:
                      msg = {"type": "connected", "connectionId": connection_id}
                      apigw.post_to_connection(
                          ConnectionId=connection_id,
                          Data=json.dumps(msg)
                      )
                      return {'statusCode': 200}
                  except Exception as e:
                      print(f"Error sending ID: {e}")
                      return {'statusCode': 500}

              return {'statusCode': 200}

  GenerateFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-Generate"
      Runtime: python3.11
      Handler: index.lambda_handler
      Timeout: 60
      MemorySize: 512
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          BUCKET_NAME: !Ref GeneratedImagesBucket
      Code:
        ZipFile: |
          import boto3
          import json
          import os
          import base64
          from io import BytesIO

          sm_client = boto3.client('sagemaker')
          runtime = boto3.client('runtime.sagemaker')
          s3_client = boto3.client('s3')

          def lambda_handler(event, context):
              try:
                  body = json.loads(event.get('body', '{}'))
                  prompt = body.get('prompt', 'a beautiful landscape')
                  connection_id = body.get('connectionId')
                  
                  endpoint_name = body.get('endpoint_name')
                  
                  if not endpoint_name:
                      return {'statusCode': 400, 'body': 'Error: Missing endpoint_name'}

                  bucket_name = os.environ['BUCKET_NAME']

                  try:
                      response = sm_client.list_inference_components(EndpointNameEquals=endpoint_name)
                      components = response.get('InferenceComponents', [])
                      inference_component = components[0]['InferenceComponentName'] if components else None
                  except Exception:
                      inference_component = None
                  
                  payload = {
                      "prompt": prompt,
                      "guidance_scale": 7.5,
                      "num_inference_steps": 30,
                  }
                  
                  invoke_args = {
                      'EndpointName': endpoint_name,
                      'ContentType': 'application/json',
                      'Accept': 'application/json;jpeg',
                      'Body': json.dumps(payload)
                  }
                  
                  if inference_component:
                      invoke_args['InferenceComponentName'] = inference_component

                  response = runtime.invoke_endpoint(**invoke_args)
                  response_body = json.loads(response['Body'].read().decode())
                  
                  if 'generated_images' in response_body:
                      image_data = response_body['generated_images'][0]
                      image_bytes = base64.b64decode(image_data)
                      
                      import time
                      file_name = f"{int(time.time())}_{connection_id}.jpg" if connection_id else f"{int(time.time())}.jpg"
                      
                      s3_client.put_object(
                          Bucket=bucket_name,
                          Key=file_name,
                          Body=image_bytes,
                          ContentType='image/jpeg'
                      )
                      return {
                          'statusCode': 200,
                          'headers': {
                              'Access-Control-Allow-Origin': '*',
                              'Access-Control-Allow-Headers': 'Content-Type',
                              'Access-Control-Allow-Methods': 'OPTIONS,POST'
                          }, 
                          'body': json.dumps({'message': 'Success', 's3_key': file_name})
                      }
                  return {'statusCode': 500, 'body': 'No image generated'}

              except Exception as e:
                  print(f"Error: {str(e)}")
                  return {'statusCode': 500, 'body': str(e)}

  NotifyFunction:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.11
      Handler: index.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          WEBSOCKET_API_ENDPOINT: !Sub "https://${WebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/${WebSocketStage}"
      Code:
        ZipFile: |
          import boto3
          import os
          import json
          from urllib.parse import unquote_plus

          s3 = boto3.client('s3')

          def lambda_handler(event, context):
              endpoint_url = os.environ['WEBSOCKET_API_ENDPOINT']
              apigw_management = boto3.client('apigatewaymanagementapi', endpoint_url=endpoint_url)
              
              for record in event['Records']:
                  key = unquote_plus(record['s3']['object']['key'])
                  bucket = record['s3']['bucket']['name']
                  try:
                      filename = key.split('/')[-1]
                      parts = filename.split('_', 1) 
                      
                      if len(parts) >= 2:
                          connection_id = parts[1].replace('.jpg', '')
                          
                          presigned_url = s3.generate_presigned_url(
                              'get_object',
                              Params={'Bucket': bucket, 'Key': key},
                              ExpiresIn=3600
                          )
                          msg = {"type": "image_generated", "image_url": presigned_url}
                          
                          print(f"Notifying {connection_id}")
                          apigw_management.post_to_connection(
                              ConnectionId=connection_id,
                              Data=json.dumps(msg)
                          )
                  except Exception as e:
                      print(f"Error notifying user: {e}")

  ShareFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-Share"
      Runtime: python3.11
      Handler: index.lambda_handler
      Timeout: 30
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          BUCKET_NAME: !Ref GeneratedImagesBucket
      Code:
        ZipFile: |
          import boto3
          import json
          import os
          import base64
          import uuid

          s3_client = boto3.client('s3')

          def lambda_handler(event, context):
              try:
                  body = json.loads(event.get('body', '{}'))
                  image_data = body.get('image_data')
                  
                  if not image_data:
                      return {'statusCode': 400, 'body': 'Missing image_data'}

                  if "base64," in image_data:
                      image_data = image_data.split("base64,")[1]

                  image_bytes = base64.b64decode(image_data)
                  bucket_name = os.environ['BUCKET_NAME']
                  
                  file_name = f"shared/{str(uuid.uuid4())}.png"

                  s3_client.put_object(
                      Bucket=bucket_name,
                      Key=file_name,
                      Body=image_bytes,
                      ContentType='image/png',
                  )

                  region = os.environ['AWS_REGION']
                  url = f"https://{bucket_name}.s3.{region}.amazonaws.com/{file_name}"

                  return {
                      'statusCode': 200,
                      'headers': {
                          'Access-Control-Allow-Origin': '*',
                          'Access-Control-Allow-Headers': 'Content-Type',
                          'Access-Control-Allow-Methods': 'OPTIONS,POST'
                      },
                      'body': json.dumps({'url': url})
                  }

              except Exception as e:
                  print(f"Error: {str(e)}")
                  return {'statusCode': 500, 'body': str(e)}

  # ==========================================================
  # 6. HTTP API
  # ==========================================================
  HttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: GenAIWorkshopHttpApi
      ProtocolType: HTTP
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowMethods:
          - POST
          - OPTIONS
        AllowHeaders:
          - Content-Type

  HttpApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref HttpApi
      StageName: $default
      AutoDeploy: true

  GenerateRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: "POST /generate"
      Target: !Join ["/", ["integrations", !Ref GenerateIntegration]]

  GenerateIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt GenerateFunction.Arn
      PayloadFormatVersion: "2.0"

  ShareRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: "POST /share"
      Target: !Join ["/", ["integrations", !Ref ShareIntegration]]

  ShareIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt ShareFunction.Arn
      PayloadFormatVersion: "2.0"

  # ==========================================================
  # 7. Triggers & Permissions
  # ==========================================================

  ConnectLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ConnectFunction
      Principal: apigateway.amazonaws.com

  GenerateLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref GenerateFunction
      Principal: apigateway.amazonaws.com

  S3BucketPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref NotifyFunction
      Principal: s3.amazonaws.com

  GeneratedImagesBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref GeneratedImagesBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "${GeneratedImagesBucket.Arn}/*"
          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub "${GeneratedImagesBucket.Arn}/*"

  ShareLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ShareFunction
      Principal: apigateway.amazonaws.com

Outputs:
  WebSocketURI:
    Description: "WebSocket Connection URL"
    Value: !Sub "wss://${WebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/${WebSocketStage}"

  RequestApiUrl:
    Description: "HTTP API URL to trigger generation"
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/"

  FrontendBucketName:
    Value: !Ref FrontendBucket
